workflows:
  unsigned-ios-build:
    name: Unsigned iOS IPA Build (Debug Mode)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_VERSION: "16.0"
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          $HOME/.bun/bin/bun --version || echo "Bun install check failed"

      - name: Install dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install

      - name: Expo Prebuild for iOS
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bunx expo prebuild --platform ios --clean
          cd ios
          pod install --repo-update

      - name: DEBUG - Show exact iOS files and schemes
        script: |
          echo "=== Contents of ios/ folder ==="
          ls -la ios/
          echo "=== xcworkspace files ==="
          ls -la ios/*.xcworkspace 2>/dev/null || echo "No .xcworkspace found"
          echo "=== xcodeproj files ==="
          ls -la ios/*.xcodeproj 2>/dev/null || echo "No .xcodeproj found"
          echo "=== List all schemes ==="
          cd ios
          xcodebuild -list || echo "xcodebuild -list failed, trying with project"
          xcodebuild -list -project *.xcodeproj 2>/dev/null || echo "No schemes listed"
          echo "=== Your app.json name/slug for reference ==="
          cat ../app.json | grep -E '"name":|"slug":'

      - name: Build unsigned archive and IPA (SKIPPED UNTIL DEBUG WORKS)
        script: |
          echo "DEBUG: Skipping build until we see correct names above. Check logs and update YAML!"

    artifacts:
      - ios/**  # Download whole ios/ folder to check manually if needed
      - build/**/*.ipa
      - build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - 10sagarhazra@gmail.com  # Your email from logs
