workflows:
  unsigned-ios-build:
    name: Unsigned iOS IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_VERSION: "16.0"
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $CM_ENV

      - name: Install dependencies
        script: |
          bun install

      - name: Expo Prebuild for iOS
        script: |
          bunx expo prebuild --platform ios --clean
          cd ios
          pod install --repo-update

      - name: Build unsigned archive and IPA
        script: |
          cd ios
          xcodebuild archive \
            -workspace gold-price-calculator-04dozbq.xcworkspace \
            -scheme gold-price-calculator-04dozbq \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath ../build/GoldPriceCalculator.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

          cd ../build/GoldPriceCalculator.xcarchive/Products/Applications
          mkdir Payload
          cp -r *.app Payload/
          cd ..
          zip -r unsigned.ipa Payload
          mv unsigned.ipa ../../..

    artifacts:
      - build/**/*.ipa
      - build/**/*.xcarchive  # Optional for debugging

    publishing:
      email:
        recipients:
          - your-email-here@gmail.com   # Change to your real email, or delete this whole publishing block
