workflows:
  unsigned-ios-build:
    name: Unsigned iOS IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_VERSION: "16.0"
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          # Quick test to confirm Bun installed
          $HOME/.bun/bin/bun --version || echo "Bun install check failed"

      - name: Install dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install

      - name: Expo Prebuild for iOS
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bunx expo prebuild --platform ios --clean
          cd ios
          pod install --repo-update

      - name: Build unsigned archive and IPA
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          cd ios
          xcodebuild archive \
            -workspace gold-price-calculator-04dozbq.xcworkspace \
            -scheme gold-price-calculator-04dozbq \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath ../build/GoldPriceCalculator.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

          # Package into IPA
          cd ../build/GoldPriceCalculator.xcarchive/Products/Applications
          mkdir Payload
          cp -r *.app Payload/
          cd ..
          zip -r unsigned.ipa Payload
          mv unsigned.ipa ../../..

          # Optional: also place a copy in build/ for better artifact detection
          cp ../../unsigned.ipa ../build/unsigned.ipa

    artifacts:
      - unsigned.ipa                     # Exact file from root
      - build/unsigned.ipa               # Copy we made in build/
      - build/**/*.ipa                   # Any other ipa files
      - build/**/*.xcarchive             # The archive itself (useful for debugging)
      - ios/*.xcworkspace                # The workspace file (debug)
      - ios/*.xcodeproj                  # The project file (debug)

    publishing:
      email:
        recipients:
          - 10sagarhazra@gmail.com       # your email – change or remove this block if you don't want emails
