workflows:
  unsigned-ios-build:
    name: Unsigned iOS IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 90  # Increased a bit for safety
    environment:
      xcode: "16.0"  # Confirmed working in logs (iphoneos18.0)
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          bun --version || echo "Bun install failed"

      - name: Clean and reinstall dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          rm -rf node_modules ios android
          bun install

      - name: Expo Prebuild for iOS
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bunx expo prebuild --platform ios --clean || echo "Prebuild failed!"
          echo "Listing ios/ directory after prebuild:"
          ls -la ios/ || echo "No ios/ directory generated!"
          cd ios || { echo "Cannot cd into ios/ - prebuild likely failed"; exit 1; }
          pod install --repo-update || echo "Pod install failed!"
          echo "Listing after pod install:"
          ls -la
          cd ..

      - name: Build unsigned archive and IPA
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          cd ios || { echo "ios/ dir missing"; exit 1; }

          # Dynamically find the .xcworkspace (in case name != expected)
          WORKSPACE=$(find . -maxdepth 1 -name "*.xcworkspace" | head -n 1 | sed 's|^\./||')
          if [ -z "$WORKSPACE" ]; then
            echo "Error: No .xcworkspace found in ios/!"
            ls -la
            exit 1
          fi
          echo "Found workspace: $WORKSPACE"

          # Also find scheme (usually matches workspace name without .xcworkspace)
          SCHEME="${WORKSPACE%.xcworkspace}"

          echo "Starting xcodebuild archive with workspace $WORKSPACE and scheme $SCHEME..."
          xcodebuild archive \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath ../build/GoldPriceCalculator.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

          cd ..
          echo "Archive step done. Listing archive contents:"
          ls -la build/GoldPriceCalculator.xcarchive || echo "No archive created!"
          echo "Listing Applications folder if exists:"
          ls -la build/GoldPriceCalculator.xcarchive/Products/Applications/ 2>/dev/null || echo "No Applications folder!"

          echo "Building IPA..."
          mkdir -p build/ipa/Payload
          cp -r build/GoldPriceCalculator.xcarchive/Products/Applications/*.app build/ipa/Payload/ 2>/dev/null || echo "No .app to copy!"
          
          echo "Payload contents:"
          ls -la build/ipa/Payload/
          
          if [ -z "$(ls -A build/ipa/Payload)" ]; then
            echo "Error: Payload empty - archive failed or no .app generated."
            exit 1
          fi
          
          cd build/ipa
          zip -r ../unsigned.ipa Payload
          cd ../..
          echo "IPA created:"
          ls -lh build/unsigned.ipa

    artifacts:
      - build/unsigned.ipa
      - build/**/*.ipa
      - build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - 10sagarhazra@gmail.com
