workflows:
  unsigned-ios-build:
    name: Unsigned iOS IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_VERSION: "16.0"
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          $HOME/.bun/bin/bun --version || echo "Bun install check failed"

      - name: Clean and reinstall dependencies
        script: |
          rm -rf node_modules ios android
          export PATH="$HOME/.bun/bin:$PATH"
          bun install

      - name: Expo Prebuild for iOS
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bunx expo prebuild --platform ios --clean
          cd ios
          pod install --repo-update

      - name: Build unsigned archive and IPA
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          cd ios
          xcodebuild archive \
            -workspace GoldPriceCalculator.xcworkspace \
            -scheme GoldPriceCalculator \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath ../build/GoldPriceCalculator.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

          cd ../build/GoldPriceCalculator.xcarchive/Products/Applications
          mkdir Payload
          cp -r *.app Payload/
          cd ..
          zip -r unsigned.ipa Payload
          mv unsigned.ipa ../../..

          cp ../../unsigned.ipa ../build/unsigned.ipa

    artifacts:
      - unsigned.ipa
      - build/unsigned.ipa
      - build/**/*.ipa
      - build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - 10sagarhazra@gmail.com
