workflows:
  unsigned-ios-build:
    name: Unsigned iOS IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: "16.0"  # Pin to compatible version (was incorrectly set as var before)
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          bun --version || echo "Bun install failed"

      - name: Clean and reinstall dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          rm -rf node_modules ios android
          bun install

      - name: Expo Prebuild for iOS
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bunx expo prebuild --platform ios --clean
          cd ios
          pod install --repo-update
          echo "Prebuild and pod install completed. Listing generated files:"
          ls -la

      - name: Build unsigned archive and IPA
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          cd ios
          echo "Starting xcodebuild archive..."
          xcodebuild archive \
            -workspace GoldPriceCalculator.xcworkspace \
            -scheme GoldPriceCalculator \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath ../build/GoldPriceCalculator.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""
          
          cd ..
          echo "Archive created. Listing contents of Applications folder:"
          ls -la build/GoldPriceCalculator.xcarchive/Products/Applications/ || echo "Warning: No Applications folder or empty!"
          
          echo "Building IPA..."
          mkdir -p build/ipa/Payload
          cp -r build/GoldPriceCalculator.xcarchive/Products/Applications/*.app build/ipa/Payload/ || echo "Warning: No .app file found to copy!"
          
          echo "Listing contents of Payload after copy:"
          ls -la build/ipa/Payload/
          
          if [ -z "$(ls -A build/ipa/Payload)" ]; then
            echo "Error: Payload is empty! No app contents copied. Failing build."
            exit 1
          fi
          
          cd build/ipa
          zip -r ../unsigned.ipa Payload
          cd ../..
          echo "Unsigned IPA created at build/unsigned.ipa"
          ls -lh build/unsigned.ipa  # Show final IPA size in logs

    artifacts:
      - build/unsigned.ipa
      - build/**/*.ipa
      - build/**/*.xcarchive

    publishing:
      email:
        recipients:
          - 10sagarhazra@gmail.com
